### ISSUE TITLE
Check data pipeline running each day

### ISSUE THREAD

**Issue by rscnt** [swb-ief/etl-pipeline#11]
- [x] Download and store the PDF for each day.
- [x] Reports from #10 are being generated daily.
- [x] Reports from #9 are being generated daily.
- [x] Reports from #9 are being generated daily.
- [x] Provide visibility and feedback of what has been downloaded and scrapped.
- [x] Make downloaded data accesible to anyone involved in the project, pdfs and csvs
